//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainRemoteControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_temperature
    {
        public string guid { get; set; }
        public string lcnum { get; set; }
        public Nullable<int> s1 { get; set; }
        public Nullable<double> t1 { get; set; }
        public Nullable<int> s2 { get; set; }
        public Nullable<double> t2 { get; set; }
        public Nullable<int> s3 { get; set; }
        public Nullable<double> t3 { get; set; }
        public Nullable<int> s4 { get; set; }
        public Nullable<double> t4 { get; set; }
        public Nullable<int> s5 { get; set; }
        public Nullable<double> t5 { get; set; }
        public Nullable<int> s6 { get; set; }
        public Nullable<double> t6 { get; set; }
        public Nullable<int> s7 { get; set; }
        public Nullable<double> t7 { get; set; }
        public Nullable<int> s8 { get; set; }
        public Nullable<double> t8 { get; set; }
        public Nullable<int> s9 { get; set; }
        public Nullable<double> t9 { get; set; }
        public Nullable<int> s10 { get; set; }
        public Nullable<double> t10 { get; set; }
        public Nullable<int> s11 { get; set; }
        public Nullable<double> t11 { get; set; }
        public Nullable<int> s12 { get; set; }
        public Nullable<double> t12 { get; set; }
        public Nullable<int> s13 { get; set; }
        public Nullable<double> t13 { get; set; }
        public Nullable<int> s14 { get; set; }
        public Nullable<double> t14 { get; set; }
        public Nullable<int> s15 { get; set; }
        public Nullable<double> t15 { get; set; }
        public Nullable<int> s16 { get; set; }
        public Nullable<double> t16 { get; set; }
        public Nullable<int> s17 { get; set; }
        public Nullable<double> t17 { get; set; }
        public Nullable<int> s18 { get; set; }
        public Nullable<double> t18 { get; set; }
        public Nullable<int> s19 { get; set; }
        public Nullable<double> t19 { get; set; }
        public Nullable<int> s20 { get; set; }
        public Nullable<double> t20 { get; set; }
        public Nullable<int> s21 { get; set; }
        public Nullable<double> t21 { get; set; }
        public Nullable<int> s22 { get; set; }
        public Nullable<double> t22 { get; set; }
        public Nullable<int> s23 { get; set; }
        public Nullable<double> t23 { get; set; }
        public Nullable<int> s24 { get; set; }
        public Nullable<double> t24 { get; set; }
        public Nullable<int> s25 { get; set; }
        public Nullable<double> t25 { get; set; }
        public Nullable<int> s26 { get; set; }
        public Nullable<double> t26 { get; set; }
        public Nullable<int> s27 { get; set; }
        public Nullable<double> t27 { get; set; }
        public Nullable<int> s28 { get; set; }
        public Nullable<double> t28 { get; set; }
        public Nullable<int> s29 { get; set; }
        public Nullable<double> t29 { get; set; }
        public Nullable<int> s30 { get; set; }
        public Nullable<double> t30 { get; set; }
        public Nullable<int> s31 { get; set; }
        public Nullable<double> t31 { get; set; }
        public Nullable<int> s32 { get; set; }
        public Nullable<double> t32 { get; set; }
        public Nullable<int> s33 { get; set; }
        public Nullable<double> t33 { get; set; }
        public Nullable<int> s34 { get; set; }
        public Nullable<double> t34 { get; set; }
        public Nullable<int> s35 { get; set; }
        public Nullable<double> t35 { get; set; }
        public Nullable<int> s36 { get; set; }
        public Nullable<double> t36 { get; set; }
        public Nullable<int> s37 { get; set; }
        public Nullable<double> t37 { get; set; }
        public Nullable<int> s38 { get; set; }
        public Nullable<double> t38 { get; set; }
        public Nullable<int> s39 { get; set; }
        public Nullable<double> t39 { get; set; }
        public Nullable<int> s40 { get; set; }
        public Nullable<double> t40 { get; set; }
        public Nullable<int> s41 { get; set; }
        public Nullable<double> t41 { get; set; }
        public Nullable<int> s42 { get; set; }
        public Nullable<double> t42 { get; set; }
        public Nullable<int> s43 { get; set; }
        public Nullable<double> t43 { get; set; }
        public Nullable<int> s44 { get; set; }
        public Nullable<double> t44 { get; set; }
        public Nullable<int> s45 { get; set; }
        public Nullable<double> t45 { get; set; }
        public Nullable<int> s46 { get; set; }
        public Nullable<double> t46 { get; set; }
        public Nullable<int> s47 { get; set; }
        public Nullable<double> t47 { get; set; }
        public Nullable<int> s48 { get; set; }
        public Nullable<double> t48 { get; set; }
        public Nullable<int> s49 { get; set; }
        public Nullable<double> t49 { get; set; }
        public Nullable<int> s50 { get; set; }
        public Nullable<double> t50 { get; set; }
        public Nullable<int> s51 { get; set; }
        public Nullable<double> t51 { get; set; }
        public Nullable<int> s52 { get; set; }
        public Nullable<double> t52 { get; set; }
        public Nullable<int> s53 { get; set; }
        public Nullable<double> t53 { get; set; }
        public Nullable<int> s54 { get; set; }
        public Nullable<double> t54 { get; set; }
        public Nullable<int> s55 { get; set; }
        public Nullable<double> t55 { get; set; }
        public Nullable<int> s56 { get; set; }
        public Nullable<double> t56 { get; set; }
        public Nullable<int> s57 { get; set; }
        public Nullable<double> t57 { get; set; }
        public Nullable<System.DateTime> sendtime { get; set; }
    
        public virtual trainInfo trainInfo { get; set; }
    }
}
