//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriticalData
    {
        public long id { get; set; }
        public string lcNum { get; set; }
        public int generatorId { get; set; }
        public double oilPress { get; set; }
        public double waterTemp { get; set; }
        public double frequency { get; set; }
        public double motorSpeed { get; set; }
        public double voltage { get; set; }
        public double current { get; set; }
        public double motorPower { get; set; }
        public double powerFactor { get; set; }
        public double oilMass { get; set; }
        public int alarmValue { get; set; }
        public System.DateTime dateTime { get; set; }
    
        public virtual trainInfo trainInfo { get; set; }
    }
}
