//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainRemoteControl.TrainWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/TrainInfoWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrainWebService.ITrainService")]
    public interface ITrainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/GetData", ReplyAction="http://tempuri.org/ITrainService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/GetTainInfoData", ReplyAction="http://tempuri.org/ITrainService/GetTainInfoDataResponse")]
        string GetTainInfoData(string lcnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/SaveInspectionRecord", ReplyAction="http://tempuri.org/ITrainService/SaveInspectionRecordResponse")]
        string SaveInspectionRecord(string Recordlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/GetTestInspectionRecord", ReplyAction="http://tempuri.org/ITrainService/GetTestInspectionRecordResponse")]
        string GetTestInspectionRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/SaveCriticalData", ReplyAction="http://tempuri.org/ITrainService/SaveCriticalDataResponse")]
        string SaveCriticalData(string Recordlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/GetTestCriticalData", ReplyAction="http://tempuri.org/ITrainService/GetTestCriticalDataResponse")]
        string GetTestCriticalData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/SaveTemperature", ReplyAction="http://tempuri.org/ITrainService/SaveTemperatureResponse")]
        string SaveTemperature(string Recordlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/GetTestTemperature", ReplyAction="http://tempuri.org/ITrainService/GetTestTemperatureResponse")]
        string GetTestTemperature();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITrainService/GetDataUsingDataContractResponse")]
        TrainRemoteControl.TrainWebService.CompositeType GetDataUsingDataContract(TrainRemoteControl.TrainWebService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrainServiceChannel : TrainRemoteControl.TrainWebService.ITrainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainServiceClient : System.ServiceModel.ClientBase<TrainRemoteControl.TrainWebService.ITrainService>, TrainRemoteControl.TrainWebService.ITrainService {
        
        public TrainServiceClient() {
        }
        
        public TrainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public string GetTainInfoData(string lcnum) {
            return base.Channel.GetTainInfoData(lcnum);
        }
        
        public string SaveInspectionRecord(string Recordlist) {
            return base.Channel.SaveInspectionRecord(Recordlist);
        }
        
        public string GetTestInspectionRecord() {
            return base.Channel.GetTestInspectionRecord();
        }
        
        public string SaveCriticalData(string Recordlist) {
            return base.Channel.SaveCriticalData(Recordlist);
        }
        
        public string GetTestCriticalData() {
            return base.Channel.GetTestCriticalData();
        }
        
        public string SaveTemperature(string Recordlist) {
            return base.Channel.SaveTemperature(Recordlist);
        }
        
        public string GetTestTemperature() {
            return base.Channel.GetTestTemperature();
        }
        
        public TrainRemoteControl.TrainWebService.CompositeType GetDataUsingDataContract(TrainRemoteControl.TrainWebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
